# Generated by Django 3.2.6 on 2021-08-10 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='size',
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fridge_app.category'),
        ),
        migrations.AddField(
            model_name='food',
            name='storage',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='unit',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
