# Generated by Django 3.2.6 on 2021-08-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0002_auto_20210810_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='storage',
            field=models.CharField(blank=True, choices=[('1', 'Refrigerate'), ('2', 'Freezer'), ('3', 'Pantry')], max_length=32, null=True),
        ),
    ]
